apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: setup-healthcheck
  namespace: dev
spec:
  default:
    checkIntervalSec: 20
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 8080
        requestPath: "/api/public/setup/v1/health"
  targetRef:
    group: ""
    kind: Service
    name: setup-svc
